const SUPABASE_URL = "https://utnngqhxpqoeatmxaujj.supabase.co"; 
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0bm5ncWh4cHFvZWF0bXhhdWpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE5Mzk1ODgsImV4cCI6MjA5NzUxNTU4OH0.DX3zS60YYFnrPKX79-ibiOHUNM9khSBLUKbimiwS5q8";

window.sb = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
